# Generated by Django 3.0.7 on 2021-03-05 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ranking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Application ID')),
                ('street_address', models.CharField(max_length=128, null=True, verbose_name='street_address')),
                ('first_name', models.CharField(max_length=128, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='Last Name')),
                ('addr_state', models.CharField(max_length=2, null=True, verbose_name='Applicant State')),
                ('annual_inc', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Applicant Annual Income')),
                ('application_type', models.CharField(max_length=128, null=True, verbose_name='Application Type')),
                ('desc', models.TextField(max_length=1028, null=True, verbose_name='Loan Description')),
                ('dti', models.DecimalField(decimal_places=4, max_digits=8, null=True, verbose_name='Debt to Income Ratio')),
                ('earliest_cr_line', models.CharField(max_length=128, null=True, verbose_name='Earliest Credit Line')),
                ('emp_length', models.CharField(max_length=128, null=True, verbose_name='Applicant Employment Length')),
                ('emp_title', models.CharField(max_length=256, null=True, verbose_name='Applicant Employer Name')),
                ('fico_range_high', models.IntegerField(null=True, verbose_name='Credit History (High)')),
                ('fico_range_low', models.IntegerField(null=True, verbose_name='Credit History (Low)')),
                ('grade', models.CharField(max_length=1, null=True, verbose_name='Loan Grade')),
                ('home_ownership', models.CharField(max_length=16, null=True, verbose_name='Applicant Home Ownership')),
                ('initial_list_status', models.CharField(max_length=16, null=True, verbose_name='Applicant Initial List Status')),
                ('installment', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Monthly Installment')),
                ('int_rate', models.DecimalField(decimal_places=4, max_digits=6, null=True, verbose_name='Interest Rate')),
                ('issue_d', models.CharField(max_length=128, null=True, verbose_name='Loan Issue Date')),
                ('loan_amnt', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Loan Amount')),
                ('loan_status', models.BooleanField(verbose_name='Loan Status')),
                ('mo_sin_old_il_acct', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Age of oldest Installment Account')),
                ('mo_sin_old_rev_tl_op', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Age of oldest Revolving Account')),
                ('mort_acc', models.IntegerField(null=True, verbose_name='Number of Mortgage Accounts')),
                ('npv', models.DecimalField(decimal_places=4, max_digits=16, null=True, verbose_name='Net Present Value')),
                ('open_acc', models.IntegerField(null=True, verbose_name='Number of Open Accounts')),
                ('policy_code', models.IntegerField(null=True, verbose_name='Loan Policy Code')),
                ('pub_rec', models.IntegerField(null=True, verbose_name='Number of Derogatory Public Records')),
                ('pub_rec_bankruptcies', models.IntegerField(null=True, verbose_name='Number of Public Record Bankruptcies')),
                ('purpose', models.CharField(max_length=128, null=True, verbose_name='Loan Purpose')),
                ('revol_bal', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Revolving Balance')),
                ('revol_util', models.DecimalField(decimal_places=2, max_digits=16, null=True, verbose_name='Revolving Utility')),
                ('term', models.IntegerField(null=True, verbose_name='Loan Term')),
                ('title', models.CharField(max_length=128, null=True, verbose_name='Loan Title')),
                ('total_acc', models.IntegerField(null=True, verbose_name='Number of Total Accounts')),
                ('verification_status', models.CharField(max_length=128, null=True, verbose_name='Applicant Verification Status')),
                ('zip_code', models.CharField(max_length=12, null=True, verbose_name='Applicant Zip Code')),
            ],
            options={
                'db_table': 'applicant',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Review ID')),
                ('decision', models.BooleanField(choices=[(True, 'Accepted'), (False, 'Rejected')], verbose_name='Decision')),
                ('date', models.DateTimeField(verbose_name='Review Date')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Applicant', verbose_name='Application ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User ID')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('applicant_id', 'user_id'), name='Unique User-Applicant Review'),
        ),
    ]